package com.xiaoyaotong.api.heartbeat.entity;

import java.util.Date;

public class ErpSettings {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_erp_settings.id
     *
     * @mbg.generated Wed Nov 20 10:02:52 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_erp_settings.company_id
     *
     * @mbg.generated Wed Nov 20 10:02:52 CST 2019
     */
    private Integer companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_erp_settings.company_name
     *
     * @mbg.generated Wed Nov 20 10:02:52 CST 2019
     */
    private String companyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_erp_settings.panel_type
     *
     * @mbg.generated Wed Nov 20 10:02:52 CST 2019
     */
    private Integer panelType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_erp_settings.create_time
     *
     * @mbg.generated Wed Nov 20 10:02:52 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_erp_settings.update_time
     *
     * @mbg.generated Wed Nov 20 10:02:52 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_erp_settings.panel_content
     *
     * @mbg.generated Wed Nov 20 10:02:52 CST 2019
     */
    private String panelContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_erp_settings.id
     *
     * @return the value of t_erp_settings.id
     *
     * @mbg.generated Wed Nov 20 10:02:52 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_erp_settings.id
     *
     * @param id the value for t_erp_settings.id
     *
     * @mbg.generated Wed Nov 20 10:02:52 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_erp_settings.company_id
     *
     * @return the value of t_erp_settings.company_id
     *
     * @mbg.generated Wed Nov 20 10:02:52 CST 2019
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_erp_settings.company_id
     *
     * @param companyId the value for t_erp_settings.company_id
     *
     * @mbg.generated Wed Nov 20 10:02:52 CST 2019
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_erp_settings.company_name
     *
     * @return the value of t_erp_settings.company_name
     *
     * @mbg.generated Wed Nov 20 10:02:52 CST 2019
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_erp_settings.company_name
     *
     * @param companyName the value for t_erp_settings.company_name
     *
     * @mbg.generated Wed Nov 20 10:02:52 CST 2019
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_erp_settings.panel_type
     *
     * @return the value of t_erp_settings.panel_type
     *
     * @mbg.generated Wed Nov 20 10:02:52 CST 2019
     */
    public Integer getPanelType() {
        return panelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_erp_settings.panel_type
     *
     * @param panelType the value for t_erp_settings.panel_type
     *
     * @mbg.generated Wed Nov 20 10:02:52 CST 2019
     */
    public void setPanelType(Integer panelType) {
        this.panelType = panelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_erp_settings.create_time
     *
     * @return the value of t_erp_settings.create_time
     *
     * @mbg.generated Wed Nov 20 10:02:52 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_erp_settings.create_time
     *
     * @param createTime the value for t_erp_settings.create_time
     *
     * @mbg.generated Wed Nov 20 10:02:52 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_erp_settings.update_time
     *
     * @return the value of t_erp_settings.update_time
     *
     * @mbg.generated Wed Nov 20 10:02:52 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_erp_settings.update_time
     *
     * @param updateTime the value for t_erp_settings.update_time
     *
     * @mbg.generated Wed Nov 20 10:02:52 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_erp_settings.panel_content
     *
     * @return the value of t_erp_settings.panel_content
     *
     * @mbg.generated Wed Nov 20 10:02:52 CST 2019
     */
    public String getPanelContent() {
        return panelContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_erp_settings.panel_content
     *
     * @param panelContent the value for t_erp_settings.panel_content
     *
     * @mbg.generated Wed Nov 20 10:02:52 CST 2019
     */
    public void setPanelContent(String panelContent) {
        this.panelContent = panelContent == null ? null : panelContent.trim();
    }
}