package com.xiaoyaotong.api.companyitem.mapper;

import org.apache.ibatis.annotations.Param;

import com.xiaoyaotong.api.companyitem.entity.CompanySkuBatch;

public interface CompanySkuBatchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_sku_batch
     *
     * @mbg.generated Tue Nov 26 15:24:11 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_sku_batch
     *
     * @mbg.generated Tue Nov 26 15:24:11 CST 2019
     */
    int insert(CompanySkuBatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_sku_batch
     *
     * @mbg.generated Tue Nov 26 15:24:11 CST 2019
     */
    int insertSelective(CompanySkuBatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_sku_batch
     *
     * @mbg.generated Tue Nov 26 15:24:11 CST 2019
     */
    CompanySkuBatch selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_sku_batch
     *
     * @mbg.generated Tue Nov 26 15:24:11 CST 2019
     */
    int updateByPrimaryKeySelective(CompanySkuBatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_sku_batch
     *
     * @mbg.generated Tue Nov 26 15:24:11 CST 2019
     */
    int updateByPrimaryKey(CompanySkuBatch record);

    Integer getCompanySkuBatchId(@Param("companyId")  int companyId,@Param("productCode") String productCode);

	int updateCompanySkuBatchById(CompanySkuBatch csku);

	int updateByCompanyIdAndProductCode(CompanySkuBatch csku);
}