package com.xiaoyaotong.api.heartbeat.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.xiaoyaotong.api.heartbeat.entity.ErpSettings;

public interface ErpSettingsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_erp_settings
     *
     * @mbg.generated Wed Nov 20 10:02:52 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_erp_settings
     *
     * @mbg.generated Wed Nov 20 10:02:52 CST 2019
     */
    int insert(ErpSettings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_erp_settings
     *
     * @mbg.generated Wed Nov 20 10:02:52 CST 2019
     */
    int insertSelective(ErpSettings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_erp_settings
     *
     * @mbg.generated Wed Nov 20 10:02:52 CST 2019
     */
    ErpSettings selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_erp_settings
     *
     * @mbg.generated Wed Nov 20 10:02:52 CST 2019
     */
    int updateByPrimaryKeySelective(ErpSettings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_erp_settings
     *
     * @mbg.generated Wed Nov 20 10:02:52 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(ErpSettings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_erp_settings
     *
     * @mbg.generated Wed Nov 20 10:02:52 CST 2019
     */
    int updateByPrimaryKey(ErpSettings record);

	int insetOrUpdateSettings(@Param("settingList") List<ErpSettings> settingList);
}