package com.xiaoyaotong.api.companyitem.entity;

import java.math.BigDecimal;
import java.util.Date;

public class CompanySkuBatch {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_sku_batch.id
     *
     * @mbg.generated Tue Nov 26 15:24:11 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_sku_batch.sku_id
     *
     * @mbg.generated Tue Nov 26 15:24:11 CST 2019
     */
    private Integer companyId;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_sku_batch.product_code
     *
     * @mbg.generated Tue Nov 26 15:24:11 CST 2019
     */
    private String companySkucode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_sku_batch.dead_line
     *
     * @mbg.generated Tue Nov 26 15:24:11 CST 2019
     */
    private String deadLine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_sku_batch.batch_no
     *
     * @mbg.generated Tue Nov 26 15:24:11 CST 2019
     */
    private String batchNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_sku_batch.stock
     *
     * @mbg.generated Tue Nov 26 15:24:11 CST 2019
     */
    private BigDecimal stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_sku_batch.price
     *
     * @mbg.generated Tue Nov 26 15:24:11 CST 2019
     */

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_sku_batch.create_user
     *
     * @mbg.generated Tue Nov 26 15:24:11 CST 2019
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_sku_batch.create_time
     *
     * @mbg.generated Tue Nov 26 15:24:11 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_sku_batch.update_user
     *
     * @mbg.generated Tue Nov 26 15:24:11 CST 2019
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_sku_batch.update_time
     *
     * @mbg.generated Tue Nov 26 15:24:11 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_sku_batch.id
     *
     * @return the value of t_company_sku_batch.id
     *
     * @mbg.generated Tue Nov 26 15:24:11 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_sku_batch.id
     *
     * @param id the value for t_company_sku_batch.id
     *
     * @mbg.generated Tue Nov 26 15:24:11 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_sku_batch.sku_id
     *
     * @return the value of t_company_sku_batch.sku_id
     *
     * @mbg.generated Tue Nov 26 15:24:11 CST 2019
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_sku_batch.dead_line
     *
     * @return the value of t_company_sku_batch.dead_line
     *
     * @mbg.generated Tue Nov 26 15:24:11 CST 2019
     */
    public String getDeadLine() {
        return deadLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_sku_batch.dead_line
     *
     * @param deadLine the value for t_company_sku_batch.dead_line
     *
     * @mbg.generated Tue Nov 26 15:24:11 CST 2019
     */
    public void setDeadLine(String deadLine) {
        this.deadLine = deadLine == null ? null : deadLine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_sku_batch.batch_no
     *
     * @return the value of t_company_sku_batch.batch_no
     *
     * @mbg.generated Tue Nov 26 15:24:11 CST 2019
     */
    public String getBatchNo() {
        return batchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_sku_batch.batch_no
     *
     * @param batchNo the value for t_company_sku_batch.batch_no
     *
     * @mbg.generated Tue Nov 26 15:24:11 CST 2019
     */
    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo == null ? null : batchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_sku_batch.stock
     *
     * @return the value of t_company_sku_batch.stock
     *
     * @mbg.generated Tue Nov 26 15:24:11 CST 2019
     */
    public BigDecimal getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_sku_batch.stock
     *
     * @param stock the value for t_company_sku_batch.stock
     *
     * @mbg.generated Tue Nov 26 15:24:11 CST 2019
     */
    public void setStock(BigDecimal stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_sku_batch.price
     *
     * @return the value of t_company_sku_batch.price
     *
     * @mbg.generated Tue Nov 26 15:24:11 CST 2019
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_sku_batch.create_user
     *
     * @return the value of t_company_sku_batch.create_user
     *
     * @mbg.generated Tue Nov 26 15:24:11 CST 2019
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_sku_batch.create_user
     *
     * @param createUser the value for t_company_sku_batch.create_user
     *
     * @mbg.generated Tue Nov 26 15:24:11 CST 2019
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_sku_batch.create_time
     *
     * @return the value of t_company_sku_batch.create_time
     *
     * @mbg.generated Tue Nov 26 15:24:11 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_sku_batch.create_time
     *
     * @param createTime the value for t_company_sku_batch.create_time
     *
     * @mbg.generated Tue Nov 26 15:24:11 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_sku_batch.update_user
     *
     * @return the value of t_company_sku_batch.update_user
     *
     * @mbg.generated Tue Nov 26 15:24:11 CST 2019
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_sku_batch.update_user
     *
     * @param updateUser the value for t_company_sku_batch.update_user
     *
     * @mbg.generated Tue Nov 26 15:24:11 CST 2019
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_sku_batch.update_time
     *
     * @return the value of t_company_sku_batch.update_time
     *
     * @mbg.generated Tue Nov 26 15:24:11 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_sku_batch.update_time
     *
     * @param updateTime the value for t_company_sku_batch.update_time
     *
     * @mbg.generated Tue Nov 26 15:24:11 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

	public Integer getCompanyId() {
		return companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	public String getCompanySkucode() {
		return companySkucode;
	}

	public void setCompanySkucode(String companySkucode) {
		this.companySkucode = companySkucode;
	}
}